### ISSUE TITLE
Dựng html trang Quản lý người dùng

### ISSUE THREAD

**Issue by anhcx0209** [vietanh-0511/ghtk-auction-laravel#21]

**Comment by anhcx0209** [comment]
@01633568287 quang
a thấy cái antd nó cũng tương tự primereact thôi. em xem tích hợp cái này vào cho anh https://www.primefaces.org/primereact/datatable/paginator/. Thay cho cái antd của em

**Comment by namtc07** [comment]
Đã render list user và delete
Đang code dở phần add user và edit user
