### ISSUE TITLE
Fix bugs

### ISSUE THREAD

**Issue by namtc07** [vietanh-0511/ghtk-auction-laravel#83]
User management:
- Ẩn password khi nhập
- Validate name lớn hơn 6 ký tự
- Create user: error không được đóng popup

Product Management
- Validate unique product name: không được trùng tên sản phẩm
- Chưa validate images
- Update: chưa lấy được value

Auction management:
- Validate unique title: không được trùng tên auction
- start_time, end_time không được trùng khi create và update

Session management
- start_price, step_price không được nhận giá trị dấu cách
- Chưa validate product, auction
- Update: error không được đóng popup

chỉnh màu cho Status: xám: preview, xanh: publish, đỏ: end

**Comment by namtc07** [comment]
@01633568287 test còn lỗi gì thì note vào đây luôn nhé

**Comment by miiajj** [comment]
- auctions hết hạn vẫn có thể đặt bid
- auctions chưa bắt đầu vẫn có thể đặt bid

**Comment by namtc07** [comment]
status code 422: Đăng nhập và Đăng ký

create user bị trả về 422
<img width="638" alt="image" src="https://user-images.githubusercontent.com/84889911/184862045-d6931946-3b69-4c41-8bad-844e29620b64.png">

update user bị trả về 422
<img width="638" alt="image" src="https://user-images.githubusercontent.com/84889911/184862544-a1287f48-368d-4d20-9ec6-cc3af8a8a63a.png"


@vietanh-0511

**Comment by vietanh-0511** [comment]
Đăng nhập sai tài khoản mật khẩu bị trả về 401:
<img width="638" alt="image" src="https://user-images.githubusercontent.com/84889911/184867078-b64a4769-6f6f-4354-a0df-b19dd962a83d.png">

@miiajj
